### ISSUE TITLE
Consider swapping head() for sample()

### ISSUE THREAD

**Issue by mialondon** [Living-with-machines/zooniverse-analysis-workshop#13]
There's a lovely bit in the notebook where people can run head(n) to see the data they've imported.

I wondered if we could change it to df.sample(n) so that a) we can note that the code is executed each time you hit play, and b) they can see more of the range of data (when it's run with bigger datasets).

**Comment by kallewesterling** [comment]
That's a great idea!

**Comment by kallewesterling** [comment]
I swapped the `.sample()` method in a couple of times. Sometimes, when you want to see the index change for instance, I think it makes more sense for the participants to see the data represented the _same_ way (but with different indices) instead.

**Comment by mialondon** [comment]
@kallewesterling nice! I think indexes can be a tricky concept as it's not always what people expect the word to mean, so that combination makes sense.
