### ISSUE TITLE
Finish notebook for H&Y

### ISSUE THREAD

**Issue by kallewesterling** [Living-with-machines/zooniverse-analysis-workshop#8]
All of these points will need to be true for [this repo's `main` branch](https://github.com/Living-with-machines/zooniverse-analysis-workshop/tree/main).
- [ ] Make sure code is finished.
- [ ] Ensure pedagogical text + intro text + whatever other meta-level information we need (license, etc.) is finished and reviewed by relevant folks (@mialondon, @kallewesterling, @GiorgiatolfoBL).
- [ ] Add notebook code to Colab with clear link to here.
- [ ] Add link to Colab from here.

**Comment by GiorgiatolfoBL** [comment]
> Make sure code is finished.
> Ensure pedagogical text + intro text + whatever other meta-level information we need (license, etc.) is finished and reviewed by relevant folks (@mialondon, @kallewesterling, @GiorgiatolfoBL).

Addressed in this pull request: https://github.com/Living-with-machines/zooniverse-analysis-workshop/pull/9

To be reviewed

**Comment by kallewesterling** [comment]
PR #9 has been merged with `main`. Thank you @GiorgiatolfoBL !
